name: Doxygen Github Pages Deploy Action
on:
  push:
    branches:
      - main

jobs:
  build-project:
    permissions:
      contents: write
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        with:
          submodules: true
      - name: Install doxygen
        uses: ssciwr/doxygen-install@v1
      - name: Configure
        uses: threeal/cmake-action@main
        with:
          build-args: "--target mostly_harmless_docs"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/html